# Generated by Django 3.1.6 on 2021-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_rooms_r_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='r_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
