# Generated by Django 3.1.6 on 2021-04-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
