# Generated by Django 3.1.6 on 2021-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
