# Generated by Django 3.1.6 on 2021-04-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
