# Generated by Django 3.1.6 on 2021-04-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rooms_r_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='r_image',
        ),
    ]
