# Generated by Django 3.1.6 on 2021-04-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20210411_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
